name: Deploy to GitHub Pagesmainブランチにプッシュされたときにワークフローを実行on:push:branches:- mainjobs:build-and-deploy:# 実行環境として最新のUbuntuを使用runs-on: ubuntu-lateststeps:# ステップ1: リポジトリのコードをチェックアウト- name: Checkout 🛎️uses: actions/checkout@v4  # ステップ2: GitHub Pagesへのデプロイを実行
  - name: Deploy 🚀
    uses: JamesIves/github-pages-deploy-action@v4
    with:
      branch: gh-pages # The branch the action should deploy to.
      folder: . # The folder the action should deploy.
